# Generated by Django 4.1.7 on 2023-05-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0011_alter_customer_profile_pic_alter_customer_user")]

    operations = [
        migrations.RemoveField(model_name="customer", name="profile_pic"),
        migrations.RemoveField(model_name="product", name="tag"),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(name="Tag"),
    ]
